name: clicktorun_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.16.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    charts_flutter: ^0.12.0
    cloud_firestore: ^3.2.1
    cupertino_icons: ^1.0.2
    firebase_auth: ^3.4.1
    firebase_core: ^1.19.1
    firebase_storage: ^10.3.1
    flutter_slidable: ^1.3.2
    font_awesome_flutter: ^10.1.0
    google_maps_flutter: ^2.1.8
    image_picker: ^0.8.5+3
    location: ^4.4.0
    shimmer: ^2.0.0
    uuid: ^3.0.6

dev_dependencies:
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/map_styles/

    fonts:
        - family: Raleway
          fonts:
              - asset: assets/fonts/Raleway-Regular.ttf
                weight: 400
              - asset: assets/fonts/Raleway-Thin.ttf
                weight: 200
              - asset: assets/fonts/Raleway-Bold.ttf
                weight: 700
              - asset: assets/fonts/Raleway-Italic.ttf
                style: italic
